name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: |
        docker build -t quiz .
        docker images
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Tag Docker image
      run: docker tag quiz ${{ secrets.DOCKER_USERNAME }}/quiz:${GITHUB_SHA}

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/quiz:${GITHUB_SHA}

    - name: Deploy to Docker environment
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/quiz:${GITHUB_SHA}
        docker stop quiz || true
        docker rm quiz || true
        docker run -d --name quiz -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/quiz:${GITHUB_SHA}












